### ISSUE TITLE
Some tips

### ISSUE THREAD

**Issue by Francisc** [taitems/Front-End-Development-Guidelines#17]
Hi and congratulations on your article.

However, I have a few comments:

1) Whitespacing & Formatting both in the JavaScript and CSS sections are mostly subjective.

2) This has no params although the comment says so:
/*
    Initiated When: zeroAsAString === 0
    Parameters: param1, param2
*/
function doHeapsOfStuff() {

}

3) Camel Case Variables: I used upper-case only names for things that I use as constants.

4) Readable Milliseconds: false, you should not make the compiler do the math each time. Just put the final result in and using inline comments show the calculations that got to the end result e.g. var secondsInOneHour=3600;//60 min_60 sec OR just 60_60

5) var bigArray = ["1000 items"]; It only has one item, which is a string. I know you meant it as bigArray[0] would imply, but I'd try to find another way like not declaring it at all as the var name is sufficient.

**Comment by taitems** [comment]
2) this section wasn't written by me (snuck in by the proofer) and is going to be completely rewritten

5) this is fixed locally, pending a commit. replaced with new Array(1000);

**Comment by exside** [comment]
1) true: and there are many "subtypes" and mix-formatting-styles (as mine...), but it's worth showing some general rules of thumb...

4) I would also do it like this and avoid another redundant calculation

**Comment by taitems** [comment]
Fixed locally, pending commit.
