### ISSUE TITLE
Caching Selector Results section code example

### ISSUE THREAD

**Issue by acusti** [taitems/Front-End-Development-Guidelines#18]
I am guessing that the following code example is not actually supposed to be using PHP style variable naming:

``` javascript
// before
var $quoteLinks = $(".quote a");  // the only DOM query
$quoteLinks.bind("click", doStuff);

// now
$quoteLinks.addClass("quoteLink");

// later
$quoteLinks.fadeIn("slow");
```

Should the first line (and subsequent references) be: `var quoteLinks = $(".quote a");` ?

**Comment by tapichu** [comment]
Some people like adding the _$_ prefix to variables that hold a jQuery object. It's a valid javascript identifier so I guess it boils down to personal preference.

**Comment by acusti** [comment]
Right on. I didn’t actually know it was a valid javascript identifier. Thanks for letting me know!
