### ISSUE TITLE
Queue - a profoundly British word

### ISSUE THREAD

**Issue by Garren** [taitems/Front-End-Development-Guidelines#21]
"Tangentially, I find it odd that what I can only assume is an American authored library uses such a profoundly British word as queue."

I'm sure you'll agree that an individual with even a basic, introductory, understanding of data-types will immediately recognize one so fundamental as a queue. Your statement, which suggests otherwise, could cause some readers to question the credibility of what you've put together. Just a thought.

**Comment by taitems** [comment]
Addressed in latest commit.

There is a long tangent of a story related to this that I'll save for a rainy day.
