### ISSUE TITLE
css shorthand, camelCasing and POSH

### ISSUE THREAD

**Issue by jalbertbowden** [taitems/Front-End-Development-Guidelines#22]
yo, nice write up! by no means am i being critical here, just wanted to point somethings out....
1. css shorthand is optimal...for making your css smaller. it is not optimal how it is presented in these guidelines. using shorthand simply because it is shorter can/will cause build-ups/bottlenecks in performance. mostly because of Reflows, Repaints,and Redraws. i agree with you actually, i prefer shorthand, but i've switched up for single property declarations for better performance/optimization. 
2. i only use camelCasing in markup for Ajax classes. and JSON classes. the camelCase denotes to developers that the class is only there for JavaScript usage, i've found this to make things quite readable, especially when fixing bugs on the fly.
   POSH and XHTML demand lower case...i realize its a new ballgame with HTML5/CSS3 but i still have yet to hear a good argument against all lowercase all the time...mostly the arguments are all about personal preference, which i understand completely. right here i am arguing my preference(s). 
   furthermore data attributes must be in lowercase, so i see no reason to deviate from the plan; mixing them up will just confuse  alot of peoples. especially if someone is researching microformats and realizes that they are (mostly) all speed in pseudo camelCase (hCard, hAudio, etc.)...i can totally see peeps thinking that a) that is how the microformats are spelled and b) bleeding those practices into other areas where lower case is a must case 

i have some more thoughts that i'll gather and get back @ ya. but this is great. nicely done sir!

**Comment by taitems** [comment]
You've reminded me to add something about "Reflows, Repaints,and Redraws". Thanks!

I welcome any more thoughts. If they're actual bugs, try and log them individually so they're easier to manage from my point of view.

**Comment by taitems** [comment]
Revisiting this one, yes, it is quite important to have lower case data names. I've run into this one quite a bit lately and will make a note of it.

**Comment by taitems** [comment]
Repaints and reflows added. Lower case data-names discussed.
