### ISSUE TITLE
CamelCase in JS variables

### ISSUE THREAD

**Issue by danburzo** [taitems/Front-End-Development-Guidelines#26]
The example you give for this section:
var MOUSE_TIMEOUT = 30;

is, i believe, a good practice: variables that are supposed to be 'constant' (stuff like intervals, timeouts) can be differentiated by using ALL_CAPS. I'm sure you meant 'variables' in the general sense, so maybe it makes sense to change the example to something like:

var ARRAY_LENGTH = myArray.length; // bad
var arrayLength = myArray.length; // good

**Comment by taitems** [comment]
Fixed locally, pending commit.
