### ISSUE TITLE
width:auto does work

### ISSUE THREAD

**Issue by blg002** [taitems/Front-End-Development-Guidelines#30]
"The better way is to set a specific width on the parent element (it doesn't work if it is "auto") and an overflow value of either auto or hidden."

I'm to lazy to look up and test this out to figure out exact situations. But I often use width:auto to help clear floats so I know it does work.

**Comment by taitems** [comment]
I think I will clarify that it's related to cross-browser compliance, as noted here: http://www.quirksmode.org/css/clearing.html

**Comment by taitems** [comment]
Addressed in latest commit.
