### ISSUE TITLE
Float Clearing should use The New Clearfix

### ISSUE THREAD

**Issue by kara-ryli** [taitems/Front-End-Development-Guidelines#4]
The problem with using `overflow: hidden` to clear floats is that in addition to clearing floats, it also hides overflow. So if you've got a heading that's supposed to hang just outside of your box, you've got a tough choice to make.

[The New Clearfix](http://perishablepress.com/press/2009/12/06/new-clearfix-hack/) method is a great way to clear floats in modern browsers, and falls back in IE the same way that the overflow trick does.

**Comment by taitems** [comment]
Not sure how I feel about browser specific CSS hacks, as that's what I set out to avoid, but I will definitely mention this.

**Comment by retlehs** [comment]
more recent (last week) and now used by html5 boilerplate: http://nicolasgallagher.com/micro-clearfix-hack/

**Comment by StommePoes** [comment]
I don't see the point of using a bunch of code to clearfix _when I can use overflow_.  IF I come to a situation where I _can't_ use overflow, I'll use clearfix.  But like most people, I prefer simple code over multi-line code (though mine is still not as large as the one at perishable press... 4 lines tops).

**Comment by exside** [comment]
+1 for the .clearfix, works great and for practical use I have switched to only use this one (mixed the overflow: hidden and .clearfix techniques before, and if you have to refactor the code a year later or so, it's a pain in the a*\* because you've forgotten where you used the overflow thing and where not^^)

**Comment by taitems** [comment]
Fixed locally, pending commit.
